/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PIO0_1_DIGIMODE_DIGITAL 0x01u  /*!<@brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_1_FUNC_ALT0 0x00u         /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO1_13_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_13_FUNC_ALT0 0x00u        /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO1_20_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_20_FUNC_ALT0 0x00u        /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO1_24_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_24_FUNC_ALT0 0x00u        /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO1_4_DIGIMODE_DIGITAL 0x01u  /*!<@brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_4_FUNC_ALT0 0x00u         /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO1_6_DIGIMODE_DIGITAL 0x01u  /*!<@brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_6_FUNC_ALT0 0x00u         /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO1_7_DIGIMODE_DIGITAL 0x01u  /*!<@brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_7_FUNC_ALT0 0x00u         /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO1_9_DIGIMODE_DIGITAL 0x01u  /*!<@brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_9_FUNC_ALT0 0x00u         /*!<@brief Selects pin function.: Alternative connection 0. */

/*! @name PIO0_1 (number 7), STN_ST
  @{ */
#define BOARD_INITPINS_CORE1_STN_ST_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE1_STN_ST_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_CORE1_STN_ST_PIN 1U    /*!<@brief 0U pin index: 1 */
                                              /* @} */

/*! @name PIO1_4 (number 1), STN_S
  @{ */
#define BOARD_INITPINS_CORE1_STN_S_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE1_STN_S_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE1_STN_S_PIN 4U    /*!<@brief 1U pin index: 4 */
                                             /* @} */

/*! @name PIO1_6 (number 5), STN_D0
  @{ */
#define BOARD_INITPINS_CORE1_STN_D0_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE1_STN_D0_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE1_STN_D0_PIN 6U    /*!<@brief 1U pin index: 6 */
                                              /* @} */

/*! @name PIO1_7 (number 9), STN_CPL
  @{ */
#define BOARD_INITPINS_CORE1_STN_CPL_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE1_STN_CPL_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE1_STN_CPL_PIN 7U    /*!<@brief 1U pin index: 7 */
                                               /* @} */

/*! @name PIO1_9 (number 10), STN_CPG
  @{ */
#define BOARD_INITPINS_CORE1_STN_CPG_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE1_STN_CPG_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE1_STN_CPG_PIN 9U    /*!<@brief 1U pin index: 9 */
                                               /* @} */

/*! @name PIO1_13 (number 2), STN_FR
  @{ */
#define BOARD_INITPINS_CORE1_STN_FR_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE1_STN_FR_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE1_STN_FR_PIN 13U   /*!<@brief 1U pin index: 13 */
                                              /* @} */

/*! @name PIO1_20 (number 4), STN_D1
  @{ */
#define BOARD_INITPINS_CORE1_STN_D1_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE1_STN_D1_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE1_STN_D1_PIN 20U   /*!<@brief 1U pin index: 20 */
                                              /* @} */

/*! @name PIO1_24 (number 3), STN_CP
  @{ */
#define BOARD_INITPINS_CORE1_STN_CP_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE1_STN_CP_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE1_STN_CP_PIN 24U   /*!<@brief 1U pin index: 24 */
                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_Core1(void); /* Function assigned for the Cortex-M33 (Core #1) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
