/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Enables digital function */
#define IOCON_PIO_DIGITAL_EN 0x0100u
/*!
 * @brief Selects pin function 1 */
#define IOCON_PIO_FUNC1 0x01u
/*!
 * @brief Input function is not inverted */
#define IOCON_PIO_INV_DI 0x00u
/*!
 * @brief No addition pin function */
#define IOCON_PIO_MODE_INACT 0x00u
/*!
 * @brief Open drain is disabled */
#define IOCON_PIO_OPENDRAIN_DI 0x00u
/*!
 * @brief Standard mode, output slew rate control is enabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_13_FUNC_ALT0 0x00u
/*!
 * @brief Controls open-drain mode.: Open-drain. Simulated open-drain output (high drive disabled). */
#define PIO0_13_OD_OPEN_DRAIN 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_14_FUNC_ALT0 0x00u
/*!
 * @brief Controls open-drain mode.: Open-drain. Simulated open-drain output (high drive disabled). */
#define PIO0_14_OD_OPEN_DRAIN 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_16_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO0_17_FUNC_ALT2 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO0_19_FUNC_ALT7 0x07u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_20_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO0_20_FUNC_ALT7 0x07u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_21_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO0_21_FUNC_ALT7 0x07u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_24_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO0_24_FUNC_ALT2 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_25_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO0_25_FUNC_ALT2 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_26_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_26_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_28_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_28_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_28_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_31_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO0_31_FUNC_ALT2 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO0_7_FUNC_ALT2 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_8_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO0_8_FUNC_ALT2 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_9_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO0_9_FUNC_ALT2 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_0_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO1_0_FUNC_ALT2 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_10_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_10_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_11_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_11_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_11_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_12_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_12_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_12_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_16_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_17_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_17_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_18_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_18_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_19_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_22_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_22_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_22_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_23_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_23_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_23_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_26_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_26_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_30_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_30_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_30_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_31_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO1_31_FUNC_ALT1 0x01u

/*! @name MCLK (number 91), MCLK
  @{ */
/* @} */

/*! @name PIO1_10 (number 40), SW_LE
  @{ */
#define BOARD_INITPINS_CORE0_SW_LE_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_SW_LE_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE0_SW_LE_PIN 10U   /*!<@brief 1U pin index: 10 */
                                             /* @} */

/*! @name PIO1_11 (number 93), HOLD
  @{ */
#define BOARD_INITPINS_CORE0_HOLD_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_HOLD_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE0_HOLD_PIN 11U   /*!<@brief 1U pin index: 11 */
                                            /* @} */

/*! @name PIO1_12 (number 67), SW_A
  @{ */
#define BOARD_INITPINS_CORE0_SW_A_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_SW_A_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE0_SW_A_PIN 12U   /*!<@brief 1U pin index: 12 */
                                            /* @} */

/*! @name PIO1_16 (number 87), LED
  @{ */
#define BOARD_INITPINS_CORE0_LED_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_LED_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE0_LED_PIN 16U   /*!<@brief 1U pin index: 16 */
                                           /* @} */

/*! @name PIO1_17 (number 43), SW_RI
  @{ */
#define BOARD_INITPINS_CORE0_SW_RI_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_SW_RI_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE0_SW_RI_PIN 17U   /*!<@brief 1U pin index: 17 */
                                             /* @} */

/*! @name PIO1_18 (number 64), EXT_PWR_GOOD
  @{ */
#define BOARD_INITPINS_CORE0_EXT_PWR_GOOD_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_EXT_PWR_GOOD_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE0_EXT_PWR_GOOD_PIN 18U   /*!<@brief 1U pin index: 18 */
                                                    /* @} */

/*! @name PIO1_19 (number 58), PMIC_ON_REQ
  @{ */
#define BOARD_INITPINS_CORE0_PMIC_ON_REQ_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_PMIC_ON_REQ_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE0_PMIC_ON_REQ_PIN 19U   /*!<@brief 1U pin index: 19 */
                                                   /* @} */

/*! @name PIO1_22 (number 41), SW_UP
  @{ */
#define BOARD_INITPINS_CORE0_SW_UP_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_SW_UP_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE0_SW_UP_PIN 22U   /*!<@brief 1U pin index: 22 */
                                             /* @} */

/*! @name PIO1_23 (number 42), SW_DN
  @{ */
#define BOARD_INITPINS_CORE0_SW_DN_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_SW_DN_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE0_SW_DN_PIN 23U   /*!<@brief 1U pin index: 23 */
                                             /* @} */

/*! @name PIO1_26 (number 68), SW_B
  @{ */
#define BOARD_INITPINS_CORE0_SW_B_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_SW_B_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE0_SW_B_PIN 26U   /*!<@brief 1U pin index: 26 */
                                            /* @} */

/*! @name PIO1_30 (number 65), SW_ST
  @{ */
#define BOARD_INITPINS_CORE0_SW_ST_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_SW_ST_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CORE0_SW_ST_PIN 30U   /*!<@brief 1U pin index: 30 */
                                             /* @} */

/*! @name PIO0_13 (number 71), I2C_SCL
  @{ */
#define BOARD_INITPINS_CORE0_I2C_SCL_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_I2C_SCL_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_CORE0_I2C_SCL_PIN 13U   /*!<@brief 0U pin index: 13 */
                                               /* @} */

/*! @name PIO0_14 (number 72), I2C_SDA
  @{ */
#define BOARD_INITPINS_CORE0_I2C_SDA_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_I2C_SDA_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_CORE0_I2C_SDA_PIN 14U   /*!<@brief 0U pin index: 14 */
                                               /* @} */

/*! @name PIO0_16 (number 14), LCD_PWR_EN
  @{ */
#define BOARD_INITPINS_CORE0_LCD_PWR_EN_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_LCD_PWR_EN_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_CORE0_LCD_PWR_EN_PIN 16U   /*!<@brief 0U pin index: 16 */
                                                  /* @} */

/*! @name PIO0_26 (number 60), PB_STAT
  @{ */
#define BOARD_INITPINS_CORE0_PB_STAT_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_PB_STAT_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_CORE0_PB_STAT_PIN 26U   /*!<@brief 0U pin index: 26 */
                                               /* @} */

/*! @name PIO0_28 (number 66), SW_SE
  @{ */
#define BOARD_INITPINS_CORE0_SW_SE_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CORE0_SW_SE_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_CORE0_SW_SE_PIN 28U   /*!<@brief 0U pin index: 28 */
                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_Core0(void); /* Function assigned for the Cortex-M33 (Core #0) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
